language: java
jdk:
  - oraclejdk7

install: true

script:
  - mvn clean verify

deploy:
  - provider: script
    script: mvn deploy
    skip_cleanup: true
    on:
      branch: master
      tags: true

branches:
  except:
    - travis
