language: java
jdk:
  - oraclejdk7

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"

install: true

script: mvn clean verify --settings target/travis/settings.xml

deploy:
  - provider: script
    script: mvn deploy --settings target/travis/settings.xml
    skip_cleanup: true
    on:
      branch: master
      tags: true
